/**
 * This file was generated by react-native-codegen.
 */

import type { TurboModule } from 'react-native';
import { TurboModuleRegistry } from 'react-native';
import type { PlaybackInfo } from '../types';

export interface Spec extends TurboModule {
  readonly initializeMediaLibrary: (
    mediaLibraryJson: string
  ) => Promise<boolean>;
  readonly updateMediaLibrary: (mediaLibraryJson: string) => Promise<boolean>;
  readonly setLayoutType: (layoutType: string) => Promise<boolean>;
  readonly refreshAndroidAutoUI: () => Promise<boolean>;
  readonly playMedia: (mediaId: string) => Promise<boolean>;
  readonly pause: () => Promise<boolean>;
  readonly resume: () => Promise<boolean>;
  readonly stop: () => Promise<boolean>;
  readonly seekTo: (positionMs: number) => Promise<boolean>;
  readonly setPlaybackSpeed: (speed: number) => Promise<boolean>;
  readonly getPlaybackState: () => Promise<PlaybackInfo>;
}

export default TurboModuleRegistry.getEnforcing<Spec>('AndroidAutoModule');
